[[main]]
  name       = 'About'
  identifier = 'about'
  pageRef    = '/about'
  weight     = 1

[[main]]
  name       = 'Research'
  identifier = 'research'
  pageRef    = '/research'
  weight     = 2

[[main]]
  name       = 'Publications'
  identifier = 'publications'
  pageRef    = '/publications'
  weight     = 3

[[main]]
  name       = 'Blog'
  identifier = 'blog'
  pageRef    = '/post'
  weight     = 4

[[footer]]
  identifier = 'email'
  url        = 'mailto:sangil.bak@chungbuk.ac.kr'
  name       = 'email'
  pre        = 'email'
  weight     = 1
